name: Publish Packages

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - uses: dotnet/nbgv@master
      id: nbgv
    - run: echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'
    - name: Publish GarciaCore.Application
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Application/GarciaCore.Application.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Application.MongoDb
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Application.MongoDb/GarciaCore.Application.MongoDb.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Application.Redis
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Application.Redis/GarciaCore.Application.Redis.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Cli
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Cli/GarciaCore.Cli.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.CodeGenerator
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.CodeGenerator/GarciaCore.CodeGenerator.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Domain
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Domain/GarciaCore.Domain.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Domain.MongoDb
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Domain.MongoDb/GarciaCore.Domain.MongoDb.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Exceptions.Redis
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Exceptions.Redis/GarciaCore.Exceptions.Redis.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Infrastructure
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Infrastructure/GarciaCore.Infrastructure.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Infrastructure.Api
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Infrastructure.Api/GarciaCore.Infrastructure.Api.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Infrastructure.MongoDb
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Infrastructure.MongoDb/GarciaCore.Infrastructure.MongoDb.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Infrastructure.Redis
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Infrastructure.Redis/GarciaCore.Infrastructure.Redis.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence/GarciaCore.Persistence.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.EntityFramework
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.EntityFramework/GarciaCore.Persistence.EntityFramework.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.MongoDb
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.MongoDb/GarciaCore.Persistence.MongoDb.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.Redis
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.Redis/GarciaCore.Persistence.Redis.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.EntityFramework.MySql
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.EntityFramework.MySql/GarciaCore.Persistence.EntityFramework.MySql.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.EntityFramework.PostgreSQL
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.EntityFramework.PostgreSQL/GarciaCore.Persistence.EntityFramework.PostgreSql.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore.Persistence.EntityFramework.SqlServer
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore.Persistence.EntityFramework.SqlServer/GarciaCore.Persistence.EntityFramework.SqlServer.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish GarciaCore
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/GarciaCore/GarciaCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{ steps.nbgv.outputs.SemVer2 }}
